# -*- coding: utf-8 -*-
"""Portafolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUhokmBQCnU_0baSlQgVfy6xKY1jCfSN
"""

# Crear archivo HTML
html = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portafolio de Belén Ordónez</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <div class="container">
        <img src="foto.jpg" alt="Foto de Belén" class="profile-img">

#descripción

        <h1>Belén Ordónez Tumi</h1>
        <p class="presentacion">
            Hola! Mi nombre es <strong>Belén Ordónez Tumi</strong> y tengo 19 años. <br>
            Soy estudiante de <strong>Comunicación para el Desarrollo</strong> en la
            <strong>Pontificia Universidad Católica del Perú</strong>. <br>
            Actualmente me encuentro en <strong>5to ciclo</strong> de mi carrera.
        </p>

        <p>
            Además de estudiar a tiempo completo, trabajo a medio tiempo en el
            <strong>Centro de Idiomas de la Universidad del Pacífico</strong> como supervisora
            de exámenes de inglés internacionales.
        </p>
# habilidades
        <h2>Habilidades</h2>
        <ul>
            <li>C1 en Inglés - Examen Aptis</li>
        </ul>

        <h2>Voluntariado</h2>
        <ul>
            <li>"Hermano menor" en la ONG CESAL</li>
        </ul>
# Contacto
        <h2>Contacto</h2>
        <p>📱 Número: 75699653</p>
        <p>📧 Correo: a20230427@pucp.edu.pe</p>
    </div>

</body>
</html>
"""

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)

# Crear archivo CSS
css = """
body {
    font-family: Arial, sans-serif;
    background-color: #fefefe;
    color: #333;
    line-height: 1.6;
    padding: 20px;
}

.container {
    max-width: 700px;
    margin: auto;
    background: #fff;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
    text-align: center;
}

.profile-img {
    width: 200px;
    height: auto;
    border-radius: 50%;
    margin-bottom: 20px;
}

h1 {
    color: #5a5a5a;
}

h2 {
    color: #007acc;
}

ul {
    list-style-type: square;
    text-align: left;
    padding-left: 20px;
}

.presentacion {
    font-size: 1.1em;
    margin-bottom: 20px;
}
"""

with open("style.css", "w", encoding="utf-8") as f:
    f.write(css)